version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/gcloud-wrapper

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: mypy checking
          command: |
            . venv/bin/activate
            mypy --allow-redefinition --ignore-missing-imports --disallow-untyped-defs --warn-redundant-casts --show-error-context \
                          --no-incremental --no-implicit-optional --html-report ./report gcloud/

      - store_artifacts:
          path: ./report
